### ISSUE TITLE
Replacing Mixin gradle plugins with your own? 

### ISSUE THREAD

**Issue by l1ving** [SpongePowered/MixinGradle#20]
I'm currently getting this error 
```
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/file/collections/SimpleFileCollection
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_init_closure4.doCall(MixinExtension.groovy:241)
	at org.spongepowered.asm.gradle.plugins.MixinExtension$_init_closure4.doCall(MixinExtension.groovy)
```
which is caused by MixinGradle 0.6 not supporting Gradle 5, which is entirely understandable given how ancient it is. 

Is there a way to replace the extension with my own? Or do I have to bundle my own Mixins fork?

**Comment by l1ving** [comment]
Nevermind, I just decided to fork Mixins.

**Comment by gabizou** [comment]
> which is caused by MixinGradle 0.6 not supporting Gradle 5, which is entirely understandable given how ancient it is.

Your problem is using 0.6, use 0.7 and upgrade Mixin to 0.8.2.

[SpongeCommon](https://github.com/SpongePowered/SpongeCommon/blob/94049ed761bd6ae01f9de7ee51924642fbccddf4/buildSrc/build.gradle.kts#L15) is [using it](https://github.com/SpongePowered/SpongeCommon/blob/94049ed761bd6ae01f9de7ee51924642fbccddf4/build.gradle.kts#L14) just [fine](https://github.com/SpongePowered/SpongeCommon/runs/1235924608?check_suite_focus=true#step:6:300) with [Gradle 5.6.4....](https://github.com/SpongePowered/SpongeCommon/blob/94049ed761bd6ae01f9de7ee51924642fbccddf4/gradle/wrapper/gradle-wrapper.properties#L3)

**Comment by l1ving** [comment]
I can't upgrade Mixin to 8, hence why I'm trying to get older Mixins to work on Gradle 5

**Comment by gabizou** [comment]
> I can't upgrade Mixin to 8

Why?

**Comment by l1ving** [comment]
Incompatibility with another, much larger mod, which people commonly use alongside mine
